/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class clearmemory_bored_cheng_clearmemoryactivity_ClearMemoryActivity */

#ifndef _Included_clearmemory_bored_cheng_clearmemoryactivity_ClearMemoryActivity
#define _Included_clearmemory_bored_cheng_clearmemoryactivity_ClearMemoryActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     clearmemory_bored_cheng_clearmemoryactivity_ClearMemoryActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_clearmemory_bored_cheng_clearmemoryactivity_ClearMemoryActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
